services:
  mongodb:
    image: mongo:7
    container_name: szzvp-db02-mongodb
    ports:
      - "27018:27017"
    volumes:
      - ./mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 5s
      timeout: 3s
      retries: 10

